import { createClient } from 'npm:@supabase/supabase-js@2.110.7';

const ALLOWED_ORIGINS = new Set(['https://alinplatform.com','https://www.alinplatform.com','https://princemuysser-jpg.github.io']);
function cors(req: Request) { const origin=req.headers.get('Origin')||''; const local=/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(origin); const allowed=ALLOWED_ORIGINS.has(origin)||local; return {...(allowed?{'Access-Control-Allow-Origin':origin}:{}),'Vary':'Origin','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Max-Age':'86400','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}; }
function json(req: Request, body: unknown, status=200){return new Response(JSON.stringify(body),{status,headers:cors(req)});}
function requestIp(req: Request){return String(req.headers.get('cf-connecting-ip')||req.headers.get('x-real-ip')||(req.headers.get('x-forwarded-for')||'').split(',')[0]||'unknown').trim().slice(0,120);}
async function sha256(value:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');}
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors(req)}); if(req.method!=='POST')return json(req,{ok:false,message:'الطريقة غير مسموحة'},405);
 const origin=req.headers.get('Origin')||''; const local=/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(origin); if(origin&&!ALLOWED_ORIGINS.has(origin)&&!local)return json(req,{ok:false,message:'المصدر غير مسموح'},403);
 try{const url=Deno.env.get('SUPABASE_URL'),serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'); if(!url||!serviceKey)throw new Error('server_not_configured'); const body=await req.json(); const phone=String(body.phone||'').trim().replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d).toString()).replace(/[^0-9+]/g,''); if(!/^\+?[0-9]{7,15}$/.test(phone))return json(req,{ok:false,message:'اكتب رقم هاتف صحيح'},400); if(String(body.confirm||'').trim()!=='DELETE')return json(req,{ok:false,message:'أكد طلب الحذف بصورة صحيحة'},400);
 const phoneHash=await sha256(`alin-delete-request-phone-v1:${phone}`),ipHash=await sha256(`alin-delete-request-ip-v1:${requestIp(req)}`),admin=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}}),since=new Date(Date.now()-86400000).toISOString(); const [{count:phoneCount,error:phoneError},{count:ipCount,error:ipError}]=await Promise.all([admin.schema('private').from('account_deletion_requests').select('id',{head:true,count:'exact'}).eq('phone_hash',phoneHash).gte('requested_at',since),admin.schema('private').from('account_deletion_requests').select('id',{head:true,count:'exact'}).eq('ip_hash',ipHash).gte('requested_at',since)]); if(phoneError||ipError)throw phoneError||ipError; if((phoneCount||0)>=3||(ipCount||0)>=8)return json(req,{ok:false,message:'تم استلام طلبات كثيرة. حاول لاحقاً.'},429);
 const {error}=await admin.schema('private').from('account_deletion_requests').insert({phone_hash:phoneHash,phone_last4:phone.replace(/\D/g,'').slice(-4),ip_hash:ipHash,status:'pending',note:'طلب حذف حساب من صفحة الويب العامة'}); if(error)throw error; return json(req,{ok:true,message:'تم استلام طلب حذف الحساب. ستراجع إدارة منصة آلين الطلب وتتحقق من ملكية الحساب قبل الحذف.'});
 }catch(error){console.error(error);return json(req,{ok:false,message:'تعذر إرسال طلب الحذف حالياً'},500);}
});
