name: alin_flutter
description: تطبيق الطالب الرسمي لمنصة آلين - Flutter
publish_to: 'none'
version: 5.4.8+14

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.16.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.3.1
  url_launcher: ^6.3.2
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/alin_logo.png
    - assets/images/alin_icon.png
