(function(){
'use strict';
if(window.ALIN_CONFIG?.teacherCoursesEnabled===false)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtDate=v=>{if(!v)return'—';try{return new Date(v+'T12:00:00').toLocaleDateString('ar-IQ')}catch(_){return v}};
const money=v=>Number(v||0).toLocaleString('ar-IQ');
const imageUrl=v=>{if(!v)return'';try{return typeof window.mediaUrl==='function'?window.mediaUrl(v):v}catch(_){return v}};
let courses=[];let sectionVisible=true;
async function load(){
  try{courses=typeof window.query==='function'?await window.query('teacher_courses',{orderBy:'created_at',ascending:false}):[];}catch(e){console.warn('[teacher courses]',e);courses=[]}
  try{const s=typeof window.query==='function'?await window.query('teacher_courses_settings'):[];sectionVisible=s?.[0]?.section_visible!==false}catch(_){sectionVisible=true}
  render();
}
function card(c){const img=imageUrl(c.cover_image_path);return `<article class="alin-course-card" data-course-id="${esc(c.id)}">${img?`<div class="alin-course-card__image"><img src="${esc(img)}" alt="${esc(c.subject||'دورة')}"></div>`:`<div class="alin-course-card__icon">${esc((c.subject||'د').slice(0,1))}</div>`}<div class="alin-course-card__body"><h3>${esc(c.subject||'دورة')}</h3><p>${esc(c.teacher_name||'مدرس')}</p><button type="button" data-course-details="${esc(c.id)}">عرض التفاصيل</button></div></article>`}
function render(){document.querySelectorAll('#alinTeacherCoursesSection').forEach(host=>{const published=courses.filter(x=>String(x.status)==='published');if(!sectionVisible||!published.length){host.hidden=true;host.innerHTML='';return}host.hidden=false;host.innerHTML=`<div class="alin-teacher-courses__head"><div><small>دورات قريبة</small><h2>دورات المدرسين</h2></div></div><div class="alin-teacher-courses__viewport">${published.slice(0,8).map(card).join('')}</div>`;host.querySelectorAll('[data-course-details]').forEach(b=>b.onclick=()=>openDetails(b.dataset.courseDetails));});}
function openDetails(id){const c=courses.find(x=>String(x.id)===String(id));if(!c)return;let modal=document.getElementById('alinTeacherCourseDetails');if(!modal){modal=document.createElement('div');modal.id='alinTeacherCourseDetails';modal.className='alin-course-details-layer';document.body.appendChild(modal)}const img=imageUrl(c.cover_image_path);modal.innerHTML=`<section class="alin-course-details"><button class="alin-course-details__close" type="button">×</button><header>${img?`<div class="alin-course-details__photo"><img src="${esc(img)}" alt="${esc(c.teacher_name||'مدرس')}"></div>`:`<div class="alin-course-details__avatar">${esc((c.teacher_name||'م').replace(/^أ\.?\s*/,'').slice(0,1))}</div>`}<div><small>تفاصيل الدورة</small><h2>${esc(c.subject||'دورة')}</h2><p>${esc(c.teacher_name||'مدرس')}</p></div></header><div class="alin-course-details__info"><div><small>اسم الدورة</small><b>${esc(c.title||'—')}</b></div>${c.grade?`<div><small>الصف</small><b>${esc(c.grade)}</b></div>`:''}<div><small>تاريخ البداية</small><b>${fmtDate(c.start_date)}</b></div><div><small>الأيام والأوقات</small><b>${esc(c.schedule_text||'يحددها المدرس')}</b></div><div><small>نوع الدورة</small><b>${esc(c.mode||'—')}</b></div><div><small>المكان</small><b>${esc(c.location||'—')}</b></div><div><small>السعر</small><b>${money(c.price)} د.ع</b></div>${c.seats!=null?`<div><small>عدد المقاعد</small><b>${esc(c.seats)}</b></div>`:''}${c.contact_phone?`<div><small>التواصل</small><b>${esc(c.contact_phone)}</b></div>`:''}</div>${c.details?`<p class="alin-course-details__desc">${esc(c.details)}</p>`:''}</section>`;modal.hidden=false;document.body.style.overflow='hidden';const close=()=>{modal.hidden=true;document.body.style.overflow=''};modal.querySelector('.alin-course-details__close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};}
window.AlinTeacherCoursesStore={load,render,openDetails};
window.addEventListener('alin:data-refreshed',load);window.addEventListener('alin:realtime-change',e=>{if(['teacher_courses','teacher_courses_settings'].includes(e.detail?.table))load()});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(load,700),{once:true});else setTimeout(load,700);
})();
