/* source: csp-mobile-inline-1.js */
(function(){try{var mode=localStorage.getItem('alin_theme_v234')==='dark'?'dark':'light';document.documentElement.dataset.alinTheme=mode;document.documentElement.dataset.alinThemeMode=mode}catch(_){document.documentElement.dataset.alinTheme='light';document.documentElement.dataset.alinThemeMode='light'}})();
/* source: csp-mobile-inline-2.js */
(function(){function unlock(){try{screen.orientation&&screen.orientation.unlock&&screen.orientation.unlock()}catch(_){}}unlock();addEventListener('pageshow',unlock,{passive:true});addEventListener('orientationchange',function(){setTimeout(unlock,50)},{passive:true})})();
/* source: csp-mobile-inline-3.js */
(function(){function apply(){var landscape=false;try{landscape=matchMedia('(orientation: landscape)').matches}catch(_){landscape=innerWidth>innerHeight}document.documentElement.dataset.alinOrientation=landscape?'landscape':'portrait';document.documentElement.style.setProperty('--alin-vw',(window.visualViewport?.width||innerWidth||0)+'px');document.documentElement.style.setProperty('--alin-vh',(window.visualViewport?.height||innerHeight||0)+'px');try{document.body&&void document.body.offsetWidth}catch(_){}}apply();addEventListener('resize',function(){requestAnimationFrame(apply)},{passive:true});addEventListener('orientationchange',function(){setTimeout(apply,80);setTimeout(apply,350)},{passive:true});window.visualViewport&&visualViewport.addEventListener('resize',function(){requestAnimationFrame(apply)},{passive:true})})();
/* source: csp-mobile-inline-4.js */
(function(){function ipad(){return /iPad/i.test(navigator.userAgent)||(/Macintosh/i.test(navigator.userAgent)&&(navigator.maxTouchPoints||0)>1)}function standalone(){return !!navigator.standalone||matchMedia('(display-mode: standalone)').matches}function refresh(){if(!ipad())return;var landscape=false;try{landscape=matchMedia('(orientation: landscape)').matches}catch(_){landscape=innerWidth>innerHeight}document.documentElement.dataset.alinOrientation=landscape?'landscape':'portrait';document.documentElement.dataset.alinDevice='tablet';document.documentElement.style.setProperty('--alin-vw',(visualViewport?.width||innerWidth||0)+'px');document.documentElement.style.setProperty('--alin-vh',(visualViewport?.height||innerHeight||0)+'px');document.body?.classList.toggle('alin-ipad-standalone',standalone());requestAnimationFrame(function(){document.body&&void document.body.offsetWidth})}['pageshow','resize','orientationchange'].forEach(function(name){addEventListener(name,function(){setTimeout(refresh,name==='orientationchange'?120:0);setTimeout(refresh,420)},{passive:true})});visualViewport&&visualViewport.addEventListener('resize',function(){requestAnimationFrame(refresh)},{passive:true});document.addEventListener('visibilitychange',function(){if(!document.hidden)setTimeout(refresh,80)});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',refresh,{once:true});else refresh()})();
/* source: csp-mobile-inline-5.js */
(function(){function apply(){try{var sw=Number(screen&&screen.width)||innerWidth||0,sh=Number(screen&&screen.height)||innerHeight||0,vw=Number(innerWidth)||sw,vh=Number(innerHeight)||sh,minEdge=Math.min(sw,sh,vw,vh),maxEdge=Math.max(sw,sh,vw,vh),touch=(navigator.maxTouchPoints||0)>0,tablet=touch&&minEdge>=540&&maxEdge>=800;document.documentElement.dataset.alinDevice=tablet?'tablet':'mobile'}catch(_){document.documentElement.dataset.alinDevice='mobile'}}apply();addEventListener('resize',apply,{passive:true});addEventListener('orientationchange',apply,{passive:true})})();
