// === courier/admin.js ===
/* ALIN v2.4.2 — courier account administration only. */
(function(){
  'use strict';
  const core=window.AlinCourierCore;if(!core)throw new Error('AlinCourierCore is required before courier/admin.js');
  const {$,$$,escv,moneyv,notify,now,allCouriers,areasOf,areaRows,statusOf,statusLabel,myOrders,financials,active,done,activeLoad,todayDone,orderState,activeCouriers,alinCouriersOptions}=core;
  function renderCouriersAdmin(){
    const rows=allCouriers(),areas=[...new Set([...areaRows().map(x=>x.name),...rows.flatMap(areasOf)])];
    const debt=rows.reduce((sum,c)=>sum+financials(c).debt,0);
    adminContent.innerHTML=`<section class="v164-admin-couriers"><header class="v164-admin-head"><div><small>نظام التوصيل</small><h2>إدارة المندوبين</h2><p>الحسابات والمناطق والحالة والطلبات والذمم من مكان واحد.</p></div><div><button onclick="adminTab('deliveryOrders')">طلبات التوصيل</button><button onclick="adminTab('courierAreas')">إدارة المناطق</button><button onclick="alinV161CourierForm()">+ إضافة مندوب</button></div></header><section class="v164-admin-metrics"><article><small>إجمالي المندوبين</small><strong>${rows.length}</strong></article><article><small>فعالون</small><strong>${rows.filter(c=>c.status!=='inactive').length}</strong></article><article><small>متاحون</small><strong>${rows.filter(c=>statusOf(c)==='available').length}</strong></article><article><small>طلبات جارية</small><strong>${rows.reduce((sum,c)=>sum+activeLoad(c),0)}</strong></article><article><small>إجمالي الذمم</small><strong>${moneyv(debt)} د.ع</strong></article></section><section class="v164-admin-tools"><input id="v216CourierQ" placeholder="بحث بالاسم أو الهاتف أو المنطقة" oninput="alinV216FilterCouriers()"><select id="v216CourierStatus" onchange="alinV216FilterCouriers()"><option value="">كل الحالات</option><option value="available">متاح</option><option value="busy">مشغول</option><option value="offline">خارج الخدمة</option><option value="inactive">موقوف</option></select><select id="v216CourierArea" onchange="alinV216FilterCouriers()"><option value="">كل المناطق</option>${areas.map(a=>`<option value="${escv(a)}">${escv(a)}</option>`).join('')}</select></section><div class="v164-admin-grid" id="v216CourierGrid">${rows.map(adminCourierCard).join('')||'<div class="empty">لا يوجد مندوبون بعد.</div>'}</div></section>`;
  }
  function adminCourierCard(c){const status=c.status==='inactive'?'inactive':statusOf(c),areas=areasOf(c),f=financials(c);return `<article class="v164-admin-card" data-search="${escv(((c.name||'')+' '+(c.phone||'')+' '+(c.username||'')+' '+areas.join(' ')).toLowerCase())}" data-status="${status}" data-areas="${escv(areas.join('|'))}"><header><div class="v161-avatar">${escv((c.name||'م').slice(0,1))}</div><div><h3>${escv(c.name||'مندوب')}</h3><p>${escv(c.phone||'بدون هاتف')} • ${escv(c.username||'بدون اسم دخول')}</p></div><span class="v161-status ${status}">${statusLabel(status)}</span></header><div class="v164-card-metrics"><div><small>الطلبات الحالية</small><b>${activeLoad(c)}</b></div><div><small>مكتملة اليوم</small><b>${todayDone(c)}</b></div><div><small>الذمة</small><b>${moneyv(f.debt)} د.ع</b></div></div><div class="v161-area-chips">${areas.map(a=>`<span>${escv(a)}</span>`).join('')||'<span>غير مرتبط بمنطقة</span>'}</div><footer><button onclick="alinV164CourierDetails('${escv(c.id)}')">التفاصيل</button><button onclick="alinV161CourierForm('${escv(c.id)}')">تعديل</button><button class="secondary" onclick="alinV164AdminStatus('${escv(c.id)}')">تغيير الحالة</button><button class="danger" onclick="alinV161ToggleCourier('${escv(c.id)}')">${c.status==='inactive'?'تفعيل':'إيقاف'}</button></footer></article>`}
  window.alinV216FilterCouriers=function(){const q=String($('#v216CourierQ')?.value||'').toLowerCase(),status=$('#v216CourierStatus')?.value||'',area=$('#v216CourierArea')?.value||'';$$('#v216CourierGrid .v164-admin-card').forEach(card=>card.hidden=!((!q||card.dataset.search.includes(q))&&(!status||card.dataset.status===status)&&(!area||card.dataset.areas.split('|').includes(area))))};
  window.alinV161CourierForm=function(id=''){
    const c=allCouriers().find(x=>String(x.id)===String(id))||{},selected=areasOf(c),box=window.checkoutBox||$('#checkoutBox'),modal=window.checkoutModal||$('#checkoutModal');if(!box||!modal)return;
    box.innerHTML=`<div class="v161-form"><h2>${id?'تعديل المندوب':'إضافة مندوب'}</h2><div class="form-grid"><input id="v161CourierName" value="${escv(c.name||'')}" placeholder="اسم المندوب"><input id="v161CourierPhone" value="${escv(c.phone||'')}" placeholder="رقم الهاتف"><input id="v161CourierUsername" value="${escv(c.username||'')}" placeholder="اسم المستخدم"><input id="v161CourierPassword" type="password" autocomplete="new-password" placeholder="${id?'كلمة مرور جديدة من 12 حرفاً (اختياري)':'كلمة مرور من 12 حرفاً وحروف وأرقام'}"><select id="v161CourierAvailability"><option value="available" ${statusOf(c)==='available'?'selected':''}>متاح</option><option value="busy" ${statusOf(c)==='busy'?'selected':''}>مشغول</option><option value="offline" ${statusOf(c)==='offline'?'selected':''}>خارج الخدمة</option></select></div><h3>مناطق العمل</h3><div class="v161-area-picker">${areaRows().map(a=>`<label><input type="checkbox" value="${escv(a.name)}" ${selected.includes(a.name)?'checked':''}> ${escv(a.name)}</label>`).join('')}</div><button onclick="alinV161SaveCourier('${escv(id)}')">حفظ المندوب</button></div>`;modal.classList.remove('hidden');
  };
  window.alinV161SaveCourier=async function(id=''){
    try{
      const name=$('#v161CourierName')?.value.trim()||'',phone=$('#v161CourierPhone')?.value.trim()||'',username=$('#v161CourierUsername')?.value.trim()||'',password=$('#v161CourierPassword')?.value||'',availability=$('#v161CourierAvailability')?.value||'available',areas=$$('.v161-area-picker input:checked').map(x=>x.value);
      if(!name||!username||(!id&&!password))throw new Error('أكمل الاسم واسم المستخدم وكلمة المرور');if(!phone)throw new Error('أدخل رقم هاتف المندوب');if(!areas.length)throw new Error('اختر منطقة عمل واحدة على الأقل');if(password&&(password.length<12||!/[0-9]/.test(password)||!/[A-Za-z\u0600-\u06FF]/.test(password)))throw new Error('كلمة المرور يجب أن تكون 12 حرفاً على الأقل وتتضمن حروفاً وأرقاماً');
      const api=window.ALINAuth;if(!api)throw new Error('خدمة الحسابات الآمنة غير جاهزة');
      const payload={role:'courier',name,username,phone,area:areas[0],areas,availability,status:'active'};if(password)payload.password=password;
      if(id)await api.updateAccountFromAdmin({account_id:id,...payload});else await api.createAccount(payload);
      if(typeof audit==='function')await audit('courier',`${id?'تعديل':'إضافة'} مندوب ${name}`);if(typeof load==='function')await load();if(typeof closeCheckout==='function')closeCheckout();renderCouriersAdmin();notify('تم حفظ حساب المندوب ومناطق عمله');
    }catch(error){alert(error.message||'تعذر حفظ المندوب')}
  };
  window.alinV161ToggleCourier=async function(id){const c=allCouriers().find(x=>String(x.id)===String(id));if(!c)return;const next=c.status==='inactive'?'active':'inactive';try{const api=window.ALINAuth;if(api?.updateAccountFromAdmin)await api.updateAccountFromAdmin({account_id:id,role:'courier',status:next,name:c.name,username:c.username,phone:c.phone,area:areasOf(c)[0]||'',areas:areasOf(c),availability:statusOf(c)});else await update('couriers',{status:next,updated_at:now()},{id});if(typeof load==='function')await load();renderCouriersAdmin()}catch(error){alert(error.message||'تعذر تحديث الحساب')}};
  window.alinV164AdminStatus=async function(id){const c=allCouriers().find(x=>String(x.id)===String(id));if(!c)return;const value=prompt('الحالة: available أو busy أو offline',statusOf(c));if(!['available','busy','offline'].includes(String(value)))return;try{await update('couriers',{availability:value,updated_at:now()},{id});if(typeof load==='function')await load();renderCouriersAdmin()}catch(error){alert(error.message||'تعذر تحديث الحالة')}};
  window.alinV164CourierDetails=function(id){const c=allCouriers().find(x=>String(x.id)===String(id)),box=window.checkoutBox||$('#checkoutBox'),modal=window.checkoutModal||$('#checkoutModal');if(!c||!box||!modal)return;const rows=myOrders(c),f=financials(c);box.innerHTML=`<section class="v164-details"><header><div class="v161-avatar">${escv((c.name||'م').slice(0,1))}</div><div><h2>${escv(c.name||'مندوب')}</h2><p>${escv(c.phone||'')} • ${escv(c.username||'')}</p></div><span class="v161-status ${statusOf(c)}">${statusLabel(statusOf(c))}</span></header><div class="v164-admin-metrics"><article><small>طلبات حالية</small><strong>${rows.filter(active).length}</strong></article><article><small>طلبات مكتملة</small><strong>${rows.filter(done).length}</strong></article><article><small>أرباحه</small><strong>${moneyv(f.earnings)} د.ع</strong></article><article><small>ذمته</small><strong>${moneyv(f.debt)} د.ع</strong></article></div><h3>مناطق العمل</h3><div class="v161-area-chips">${areasOf(c).map(a=>`<span>${escv(a)}</span>`).join('')}</div><h3>آخر الطلبات</h3><div class="v164-mini-orders">${rows.slice(0,8).map(o=>`<div><span>${escv(o.order_number||o.id)}</span><span>${escv(o.delivery_area||'')}</span><b>${moneyv(o.total)} د.ع</b><small>${escv(orderState(o.status))}</small></div>`).join('')||'<p class="empty">لا توجد طلبات.</p>'}</div></section>`;modal.classList.remove('hidden')};


  window.renderCouriersAdmin=renderCouriersAdmin;
  window.activeCouriers=activeCouriers;
  window.alinCouriersOptions=alinCouriersOptions;
  window.addCourier=()=>window.alinV161CourierForm();
  window.toggleCourier=window.alinV161ToggleCourier;
  Object.assign(window.AlinCourierModules,{activeCouriers,renderCouriersAdmin,addCourier:window.addCourier,toggleCourier:window.toggleCourier,alinCouriersOptions});
  window.AlinAdminModules?.register?.('couriers',renderCouriersAdmin);
})();

;
